export const dummyUser = {
  id: 1,
  name: 'John Doe',
  email: 'john.doe@student.edu',
  studentId: 'STU2024001',
  avatar: 'https://via.placeholder.com/150',
  department: 'Computer Science',
  year: '3rd Year',
  enrolledDate: '2024-01-15',
};

export const dummyPrograms = [
  {
    id: 1,
    name: 'Bachelor of Computer Science',
    code: 'BCS2024',
    duration: '4 Years',
    totalCourses: 48,
    completedCourses: 32,
    progress: 67,
    status: 'enrolled',
    description: 'Comprehensive program covering software development, algorithms, and computer systems.',
    startDate: '2024-01-15',
    endDate: '2027-12-15',
  },
  {
    id: 2,
    name: 'Web Development Certificate',
    code: 'WDC2024',
    duration: '6 Months',
    totalCourses: 8,
    completedCourses: 3,
    progress: 38,
    status: 'enrolled',
    description: 'Focused program on modern web development technologies.',
    startDate: '2024-03-01',
    endDate: '2024-08-31',
  },
  {
    id: 3,
    name: 'Data Science Fundamentals',
    code: 'DSF2024',
    duration: '1 Year',
    totalCourses: 12,
    completedCourses: 0,
    progress: 0,
    status: 'available',
    description: 'Introduction to data science and machine learning concepts.',
    startDate: '2024-09-01',
    endDate: '2025-08-31',
  },
];

export const dummyCourses = [
  {
    id: 1,
    programId: 1,
    name: 'Introduction to Programming',
    code: 'CS101',
    instructor: 'Dr. Sarah Johnson',
    credits: 3,
    duration: '16 weeks',
    status: 'completed',
    progress: 100,
    description: 'Fundamental programming concepts using Python.',
    topics: [
      {
        id: 1,
        title: 'Variables and Data Types',
        duration: '2 weeks',
        materials: [
          { id: 1, name: 'Variables.pdf', type: 'pdf', size: '2.5MB' },
          { id: 2, name: 'Data Types.pptx', type: 'ppt', size: '1.8MB' },
        ],
      },
      {
        id: 2,
        title: 'Control Structures',
        duration: '3 weeks',
        materials: [
          { id: 3, name: 'Control Structures.pdf', type: 'pdf', size: '3.2MB' },
          { id: 4, name: 'Loops.mp4', type: 'video', size: '45MB' },
        ],
      },
    ],
  },
  {
    id: 2,
    programId: 1,
    name: 'Data Structures and Algorithms',
    code: 'CS201',
    instructor: 'Prof. Michael Chen',
    credits: 4,
    duration: '16 weeks',
    status: 'in-progress',
    progress: 65,
    description: 'Advanced data structures and algorithm analysis.',
    topics: [
      {
        id: 3,
        title: 'Arrays and Linked Lists',
        duration: '4 weeks',
        materials: [
          { id: 5, name: 'Arrays.pdf', type: 'pdf', size: '4.1MB' },
          { id: 6, name: 'Linked Lists.mp4', type: 'video', size: '52MB' },
        ],
      },
      {
        id: 4,
        title: 'Trees and Graphs',
        duration: '5 weeks',
        materials: [
          { id: 7, name: 'Trees.pdf', type: 'pdf', size: '5.2MB' },
          { id: 8, name: 'Graphs.pptx', type: 'ppt', size: '3.1MB' },
        ],
      },
    ],
  },
  {
    id: 3,
    programId: 2,
    name: 'React Native Development',
    code: 'WD301',
    instructor: 'Alex Rodriguez',
    credits: 3,
    duration: '12 weeks',
    status: 'in-progress',
    progress: 40,
    description: 'Mobile app development using React Native.',
    topics: [
      {
        id: 5,
        title: 'React Native Basics',
        duration: '3 weeks',
        materials: [
          { id: 9, name: 'RN Basics.pdf', type: 'pdf', size: '3.8MB' },
          { id: 10, name: 'Setup Guide.mp4', type: 'video', size: '38MB' },
        ],
      },
    ],
  },
];

export const dummyMaterials = [
  {
    id: 1,
    name: 'Variables.pdf',
    type: 'pdf',
    size: '2.5MB',
    courseId: 1,
    topicId: 1,
    downloadUrl: 'https://example.com/materials/variables.pdf',
    uploadedAt: '2024-01-20',
    downloaded: true,
  },
  {
    id: 2,
    name: 'Data Types.pptx',
    type: 'ppt',
    size: '1.8MB',
    courseId: 1,
    topicId: 1,
    downloadUrl: 'https://example.com/materials/data-types.pptx',
    uploadedAt: '2024-01-22',
    downloaded: false,
  },
  {
    id: 3,
    name: 'Control Structures.pdf',
    type: 'pdf',
    size: '3.2MB',
    courseId: 1,
    topicId: 2,
    downloadUrl: 'https://example.com/materials/control-structures.pdf',
    uploadedAt: '2024-02-01',
    downloaded: true,
  },
  {
    id: 4,
    name: 'Loops.mp4',
    type: 'video',
    size: '45MB',
    courseId: 1,
    topicId: 2,
    downloadUrl: 'https://example.com/materials/loops.mp4',
    uploadedAt: '2024-02-05',
    downloaded: false,
  },
];

export const dummyAssignments = [
  {
    id: 1,
    courseId: 1,
    title: 'Variables and Data Types Assignment',
    description: 'Create a Python program that demonstrates the use of different data types.',
    dueDate: '2024-02-15',
    status: 'submitted',
    submittedAt: '2024-02-14',
    grade: 85,
    maxGrade: 100,
    files: [
      { id: 1, name: 'assignment1.py', type: 'python', size: '2.1KB' },
    ],
    comments: 'Good work! Make sure to add more comments in your code.',
  },
  {
    id: 2,
    courseId: 1,
    title: 'Control Structures Project',
    description: 'Build a simple calculator using if-else statements and loops.',
    dueDate: '2024-03-01',
    status: 'pending',
    submittedAt: null,
    grade: null,
    maxGrade: 100,
    files: [],
    comments: '',
  },
  {
    id: 3,
    courseId: 2,
    title: 'Array Implementation',
    description: 'Implement basic array operations in your preferred programming language.',
    dueDate: '2024-03-10',
    status: 'draft',
    submittedAt: null,
    grade: null,
    maxGrade: 100,
    files: [
      { id: 2, name: 'array_ops.java', type: 'java', size: '5.3KB' },
    ],
    comments: '',
  },
];

export const dummyExams = [
  {
    id: 1,
    courseId: 1,
    title: 'Midterm Exam - Programming Fundamentals',
    description: 'Covers variables, data types, and basic control structures.',
    duration: 60, // minutes
    totalQuestions: 25,
    status: 'completed',
    score: 88,
    maxScore: 100,
    startTime: '2024-02-20T10:00:00Z',
    endTime: '2024-02-20T11:00:00Z',
    questions: [
      {
        id: 1,
        type: 'multiple_choice',
        question: 'Which of the following is a valid Python variable name?',
        options: ['2variable', '_variable', 'variable-2', 'class'],
        correctAnswer: 1,
        selectedAnswer: 1,
      },
      {
        id: 2,
        type: 'true_false',
        question: 'In Python, strings are immutable.',
        correctAnswer: true,
        selectedAnswer: true,
      },
    ],
  },
  {
    id: 2,
    courseId: 2,
    title: 'Data Structures Quiz',
    description: 'Test your knowledge of arrays and linked lists.',
    duration: 45,
    totalQuestions: 20,
    status: 'upcoming',
    score: null,
    maxScore: 100,
    startTime: '2024-03-15T14:00:00Z',
    endTime: '2024-03-15T14:45:00Z',
    questions: [],
  },
]; 